{% set name = "jupyterlab-classic" %}
{% set version = "0.1.2" %}
{% set sha256 = "a9d0efc292f8c9352e91838cd7f57ef540e97d439e00534b64102667c03e23db" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-classic = jupyterlab_classic.app:main

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging >=0.7.9

  run:
    - python >=3.6
    - jupyterlab >=3.0.0,<4

test:
  imports:
    - jupyterlab_classic
  commands:
    - pip check
    - jupyter classic --help
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/jtpio/jupyterlab-classic
  summary: The next-gen old-school notebook UI
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    The next-gen old-school notebook UI
  dev_url: https://github.com/jtpio/jupyterlab-classic

extra:
  recipe-maintainers:
    - jtpio
