{% set name = "jupyterlab-classic" %}
{% set version = "0.1.7" %}
{% set sha256 = "a675604ad066f187efa07dc4494747ba8b57c07d26738683c96bbc49634c4445" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-classic = jupyterlab_classic.app:main

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6

  run:
    - nbclassic >=0.2,<1
    - jupyterlab >=3.0.0,<4
    - jupyterlab_server >=2.3,<3
    - jupyter_server >=1.4,<2
    - python >=3.6
    - tornado >=6.1

test:
  imports:
    - jupyterlab_classic
  commands:
    - pip check
    - jupyter classic --help
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/jtpio/jupyterlab-classic
  summary: The next-gen old-school notebook UI
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    The next-gen old-school notebook UI
  dev_url: https://github.com/jtpio/jupyterlab-classic

extra:
  recipe-maintainers:
    - jtpio
